Remove-Item -LiteralPath "C:\Projects\Group-12-Project-CSCE3444-fa25\src\server\README.md" -Force
Remove-Item -LiteralPath "C:\Projects\Group-12-Project-CSCE3444-fa25\src\guidelines\Guidelines.md" -Force
Remove-Item -LiteralPath "C:\Projects\Group-12-Project-CSCE3444-fa25\src\SERVER_INTEGRATION_COMPLETE.md" -Force
Remove-Item -LiteralPath "C:\Projects\Group-12-Project-CSCE3444-fa25\src\README.md" -Force
Remove-Item -LiteralPath "C:\Projects\Group-12-Project-CSCE3444-fa25\src\QUICK_REFERENCE.md" -Force
Remove-Item -LiteralPath "C:\Projects\Group-12-Project-CSCE3444-fa25\src\DEPLOYMENT_READY.md" -Force
Remove-Item -LiteralPath "C:\Projects\Group-12-Project-CSCE3444-fa25\src\DEPLOYMENT_GUIDE.md" -Force
Remove-Item -LiteralPath "C:\Projects\Group-12-Project-CSCE3444-fa25\src\DEPLOYMENT_CHECKLIST.md" -Force
Remove-Item -LiteralPath "C:\Projects\Group-12-Project-CSCE3444-fa25\src\DAILY_PUZZLE_SYNC.md" -Force
Remove-Item -LiteralPath "C:\Projects\Group-12-Project-CSCE3444-fa25\src\Attributions.md" -Force
Remove-Item -LiteralPath "C:\Projects\Group-12-Project-CSCE3444-fa25\src\ARCHITECTURE.md" -Force
Remove-Item -LiteralPath "C:\Projects\Group-12-Project-CSCE3444-fa25\README.md" -Force
Remove-Item -LiteralPath "C:\Projects\Group-12-Project-CSCE3444-fa25\delete_md_files.ps1" -Force